language: rust
rust:
 - stable
 - beta
 - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
env:
  - RUST_BACKTRACE=1
script:
  - cargo build --verbose --release
  - cargo test --verbose --release --jobs 1
