use std::str::FromStr;

use strum::EnumString;

#[derive(Clone, Copy, Debug, Eq, PartialEq, EnumString)]
#[strum(serialize_all = "lowercase")]
enum CommandName {
    Forward,
    Down,
    Up,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct Command {
    name: CommandName,
    amount: i32,
}

impl FromStr for Command {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let (cmd_str, amount_str) = s.split_once(' ').ok_or(())?;
        Ok(Command {
            name: cmd_str.parse().map_err(|_| ())?,
            amount: amount_str.parse().map_err(|_| ())?,
        })
    }
}

pub fn star1(input: &str) -> String {
    let mut fwd = 0;
    let mut depth = 0;

    for cmd in input.lines().map(|l| l.parse::<Command>().unwrap()) {
        match cmd.name {
            CommandName::Forward => fwd += cmd.amount,
            CommandName::Down => depth += cmd.amount,
            CommandName::Up => depth -= cmd.amount,
        }
    }

    (fwd * depth).to_string()
}

pub fn star2(input: &str) -> String {
    let mut fwd = 0;
    let mut depth = 0;
    let mut aim = 0;

    for cmd in input.lines().map(|l| l.parse::<Command>().unwrap()) {
        match cmd.name {
            CommandName::Forward => {
                fwd += cmd.amount;
                depth += aim * cmd.amount;
            }
            CommandName::Down => aim += cmd.amount,
            CommandName::Up => aim -= cmd.amount,
        }
    }

    (fwd * depth).to_string()
}

#[cfg(test)]
mod test {
    use super::*;
    use indoc::indoc;

    star_test!(example1a, star1, IN1, "150");
    star_test!(me1, star1, ME, "1728414");

    star_test!(example1b, star2, IN1, "900");
    star_test!(me2, star2, ME, "1765720035");

    const IN1: &str = indoc! {"
        forward 5
        down 5
        forward 8
        up 3
        down 8
        forward 2
    "};

    const ME: &str = indoc! {"
        forward 9
        down 9
        down 6
        up 2
        down 5
        forward 3
        forward 6
        forward 8
        down 8
        up 4
        down 5
        down 4
        up 6
        down 7
        forward 5
        forward 5
        down 9
        down 5
        up 4
        forward 1
        forward 7
        down 8
        up 2
        down 1
        down 3
        up 7
        up 5
        down 8
        down 6
        forward 9
        up 8
        down 4
        forward 9
        forward 4
        forward 1
        up 9
        forward 5
        forward 1
        down 2
        down 7
        forward 5
        up 8
        forward 1
        down 9
        down 3
        forward 6
        up 6
        down 4
        forward 6
        down 3
        forward 5
        forward 1
        down 3
        forward 3
        down 8
        down 2
        forward 8
        forward 1
        up 4
        forward 4
        down 1
        down 5
        forward 2
        forward 9
        forward 5
        down 2
        up 9
        forward 2
        down 2
        down 2
        down 9
        up 8
        down 3
        forward 8
        down 4
        up 3
        down 1
        forward 7
        down 7
        forward 9
        down 2
        up 9
        up 3
        down 2
        up 2
        forward 8
        down 3
        forward 2
        forward 6
        down 5
        up 9
        forward 6
        forward 7
        down 3
        forward 1
        down 2
        forward 8
        up 5
        down 6
        forward 1
        down 8
        down 5
        forward 4
        down 5
        forward 3
        forward 5
        up 3
        down 4
        down 8
        up 7
        down 7
        forward 3
        down 2
        forward 3
        up 2
        down 1
        up 2
        forward 4
        forward 2
        down 1
        up 9
        forward 5
        forward 7
        down 6
        down 3
        down 5
        down 4
        up 4
        forward 8
        down 6
        forward 1
        forward 6
        down 8
        down 2
        down 3
        up 8
        forward 9
        down 5
        down 6
        forward 7
        down 2
        forward 6
        up 3
        up 6
        forward 2
        up 8
        up 2
        up 4
        forward 3
        forward 4
        down 7
        up 1
        forward 5
        forward 1
        forward 9
        forward 8
        up 6
        forward 4
        forward 2
        up 9
        forward 8
        down 2
        forward 4
        forward 4
        forward 6
        down 3
        forward 8
        forward 7
        forward 6
        forward 3
        down 5
        down 3
        forward 4
        forward 7
        forward 4
        forward 3
        forward 1
        forward 1
        up 1
        down 4
        up 5
        up 4
        up 8
        forward 7
        forward 4
        forward 3
        up 6
        up 4
        down 4
        up 4
        down 6
        forward 1
        forward 5
        up 3
        forward 5
        up 9
        down 9
        forward 1
        down 3
        forward 7
        up 2
        up 1
        down 8
        forward 9
        forward 3
        forward 2
        forward 6
        down 2
        forward 4
        up 9
        forward 6
        forward 8
        down 5
        down 6
        forward 7
        forward 5
        forward 6
        forward 9
        forward 5
        up 3
        forward 2
        forward 2
        forward 8
        down 5
        forward 9
        forward 7
        forward 5
        up 2
        up 7
        forward 7
        forward 9
        down 9
        up 5
        up 5
        up 1
        forward 8
        forward 3
        forward 2
        forward 4
        down 7
        down 7
        forward 7
        down 2
        forward 4
        down 6
        down 8
        down 5
        down 9
        forward 1
        forward 4
        forward 1
        forward 1
        up 5
        down 5
        up 7
        up 7
        down 6
        down 5
        forward 9
        up 7
        down 2
        down 9
        down 9
        forward 3
        up 9
        down 7
        down 2
        up 6
        down 9
        down 6
        up 3
        up 6
        forward 4
        forward 6
        down 2
        up 3
        down 3
        forward 8
        up 1
        forward 8
        forward 5
        forward 4
        forward 9
        forward 8
        up 1
        forward 2
        down 8
        up 9
        forward 3
        forward 9
        down 3
        down 8
        down 5
        up 5
        up 3
        down 5
        down 4
        down 2
        forward 1
        forward 8
        down 3
        down 1
        down 5
        down 1
        up 1
        down 4
        forward 6
        down 5
        down 7
        forward 4
        down 2
        down 2
        up 1
        forward 9
        down 2
        forward 7
        up 4
        down 8
        down 5
        up 2
        down 7
        forward 7
        up 4
        down 8
        forward 9
        up 3
        down 9
        forward 4
        forward 5
        up 6
        forward 5
        down 6
        down 3
        down 1
        down 6
        forward 7
        forward 3
        forward 4
        up 8
        forward 7
        down 3
        up 2
        up 3
        up 5
        forward 4
        forward 9
        forward 1
        down 2
        forward 4
        forward 1
        forward 6
        down 6
        forward 8
        down 2
        forward 7
        down 5
        forward 6
        down 4
        down 8
        down 6
        forward 9
        forward 2
        forward 4
        forward 9
        down 1
        down 9
        forward 2
        down 3
        forward 2
        down 4
        down 6
        up 5
        forward 9
        forward 1
        down 1
        forward 8
        forward 7
        forward 2
        forward 4
        forward 3
        up 8
        down 4
        forward 5
        up 5
        forward 4
        up 5
        forward 7
        up 7
        forward 5
        down 3
        up 9
        up 2
        forward 9
        forward 8
        forward 7
        down 8
        forward 8
        down 2
        forward 7
        forward 4
        down 7
        up 4
        forward 2
        forward 1
        up 5
        forward 5
        down 5
        down 1
        down 7
        up 6
        down 5
        down 6
        forward 2
        forward 2
        forward 8
        down 9
        down 4
        down 3
        forward 7
        forward 6
        forward 5
        up 9
        forward 8
        forward 9
        forward 4
        down 9
        down 6
        down 2
        down 7
        up 3
        forward 3
        forward 5
        up 6
        down 7
        down 3
        forward 3
        down 5
        down 2
        down 4
        up 4
        down 5
        forward 3
        forward 1
        forward 7
        down 7
        forward 8
        up 7
        forward 3
        forward 8
        down 9
        down 1
        forward 4
        forward 4
        forward 5
        forward 6
        down 5
        down 6
        forward 6
        down 5
        down 7
        forward 2
        down 1
        down 8
        down 3
        down 4
        forward 9
        forward 4
        down 4
        up 4
        down 3
        forward 5
        down 4
        forward 3
        forward 9
        up 7
        down 5
        down 1
        forward 8
        down 2
        forward 9
        forward 6
        forward 3
        down 7
        forward 2
        forward 5
        down 6
        forward 1
        forward 7
        up 1
        forward 3
        forward 7
        forward 3
        forward 5
        down 5
        forward 6
        forward 9
        up 4
        forward 6
        forward 3
        down 9
        up 4
        up 6
        down 5
        down 8
        down 2
        down 9
        forward 8
        up 8
        forward 3
        forward 8
        up 8
        down 5
        down 9
        down 1
        down 3
        forward 3
        forward 9
        up 9
        down 5
        down 6
        down 1
        forward 9
        up 3
        forward 3
        forward 9
        down 7
        down 4
        down 5
        up 5
        forward 2
        down 5
        up 5
        up 4
        up 5
        forward 1
        down 2
        forward 7
        down 9
        forward 8
        forward 7
        forward 5
        down 3
        forward 5
        forward 7
        forward 1
        up 5
        forward 3
        forward 1
        down 1
        up 1
        down 7
        up 4
        forward 8
        up 9
        down 9
        down 9
        forward 8
        forward 3
        forward 3
        up 4
        down 3
        forward 4
        forward 6
        forward 7
        down 2
        forward 5
        down 3
        down 9
        down 4
        down 4
        forward 3
        down 3
        down 6
        up 5
        up 4
        down 6
        up 9
        down 9
        up 2
        up 1
        down 3
        forward 6
        up 6
        forward 1
        down 9
        down 6
        down 8
        down 9
        down 6
        forward 4
        up 6
        down 2
        forward 9
        forward 2
        down 4
        up 3
        forward 6
        down 2
        down 7
        down 1
        up 6
        down 5
        forward 1
        forward 7
        up 9
        forward 2
        up 8
        down 4
        forward 8
        up 2
        up 2
        down 1
        forward 6
        down 3
        forward 7
        forward 2
        down 5
        down 6
        up 8
        forward 4
        up 2
        forward 7
        forward 4
        forward 2
        down 1
        forward 7
        down 1
        up 1
        down 9
        forward 5
        forward 3
        down 6
        up 5
        up 9
        down 1
        forward 2
        forward 8
        down 5
        down 4
        forward 6
        forward 1
        forward 4
        forward 2
        forward 4
        up 7
        forward 5
        forward 2
        down 2
        forward 1
        forward 4
        down 4
        forward 7
        down 6
        forward 9
        forward 9
        forward 3
        up 5
        up 5
        down 6
        forward 7
        forward 8
        down 5
        forward 6
        forward 5
        forward 1
        forward 7
        forward 6
        up 2
        up 4
        forward 6
        down 4
        down 9
        forward 9
        down 4
        up 2
        down 5
        forward 9
        down 7
        forward 9
        up 9
        forward 9
        up 7
        up 2
        up 6
        forward 1
        up 9
        down 4
        down 8
        forward 8
        forward 7
        up 5
        forward 4
        down 3
        down 5
        up 9
        up 5
        forward 1
        down 3
        down 9
        up 2
        forward 5
        down 8
        down 3
        forward 5
        up 8
        forward 1
        forward 8
        forward 6
        down 2
        down 8
        down 8
        down 8
        forward 8
        forward 9
        up 2
        up 9
        up 8
        forward 2
        down 4
        up 7
        down 3
        forward 1
        forward 7
        down 8
        down 2
        forward 6
        forward 2
        down 6
        down 6
        up 9
        forward 9
        down 7
        forward 7
        down 4
        up 2
        up 7
        down 8
        forward 6
        up 2
        forward 4
        forward 9
        down 7
        forward 4
        up 4
        forward 8
        down 4
        forward 6
        forward 8
        down 2
        down 6
        up 4
        forward 5
        forward 1
        down 2
        up 6
        down 6
        down 3
        up 2
        up 4
        forward 1
        up 3
        up 5
        down 4
        down 1
        down 7
        down 7
        down 4
        forward 7
        down 9
        down 4
        down 2
        down 7
        forward 7
        forward 8
        forward 1
        down 8
        down 3
        down 5
        down 8
        forward 7
        forward 9
        forward 3
        up 8
        forward 5
        up 5
        up 2
        forward 4
        forward 6
        down 8
        down 1
        up 6
        forward 5
        forward 5
        down 9
        forward 3
        up 1
        down 1
        forward 5
        forward 5
        up 5
        down 4
        up 6
        forward 8
        forward 6
        up 5
        forward 2
        up 3
        forward 9
        forward 5
        down 9
        forward 3
        forward 1
        forward 4
        up 5
        forward 3
        forward 3
        up 9
        down 2
        down 3
        down 1
        forward 8
        down 4
        forward 8
        forward 8
        down 8
        forward 9
        forward 8
        forward 7
        down 6
        forward 5
        down 6
        up 8
        forward 6
        down 8
        forward 8
        down 6
        up 2
        forward 5
        forward 1
        up 2
        forward 4
        down 5
        up 8
        up 3
        forward 8
        down 3
        forward 4
        up 5
        forward 2
        down 3
        down 2
        down 7
        forward 5
        down 5
        forward 2
        up 1
        down 3
        down 9
        up 4
        up 3
        down 8
        up 1
        down 5
        down 5
        forward 7
        up 2
        down 3
        up 3
        forward 1
        forward 4
        forward 3
        up 5
        down 5
        up 3
        down 2
        forward 6
        down 6
        up 3
        forward 9
        down 9
        up 4
        down 4
        down 6
        up 9
        forward 3
        forward 2
        up 2
        up 5
        forward 2
        up 5
        forward 7
        down 8
        down 7
        up 8
        down 1
        up 1
        up 9
        forward 7
        forward 5
        down 9
        forward 8
        down 8
        forward 4
        forward 1
        forward 2
        down 8
        forward 3
        forward 6
        down 9
        forward 2
        forward 9
        down 4
        down 1
        down 1
        down 8
        down 1
        down 4
        up 3
        down 7
        down 5
        forward 1
        forward 5
        forward 8
        forward 4
        down 7
        down 6
        forward 2
        down 3
        down 3
        down 3
        forward 5
        forward 7
        down 4
        forward 6
        forward 9
        down 1
        forward 7
        down 5
        up 4
        up 5
        down 3
        down 1
        up 5
        forward 4
        down 9
        down 7
        up 1
        up 9
        up 4
        forward 7
        down 5
        down 8
        forward 5
        forward 9
        down 2
        down 7
        forward 8
        forward 7
        down 6
        down 8
        forward 3
        forward 6
        down 5
        forward 7
        up 7
        down 8
        forward 9
        down 3
        up 3
        forward 4
        up 4
        forward 3
        forward 4
        forward 9
        forward 5
        down 3
        down 6
        forward 9
        forward 4
        forward 1
        forward 7
        forward 8
        forward 2
        forward 7
        up 9
        down 8
        forward 4
        forward 4
        down 5
        forward 2
        forward 5
        down 6
        forward 4
        forward 2
        forward 7
        down 6
        down 2
        down 5
        down 1
        forward 5
    "};
}
